"""Svensson pins, ported from Java SvenssonTest.

Planted-parameter recovery, exact NS nesting on b3 = 0 data, and the
raison d'etre — a two-hump curve plain Nelson-Siegel cannot bend into,
fitted head-to-head.
"""

import pytest

from quantfinlib.rates import NelsonSiegel, Svensson

TENORS = [0.25, 0.5, 1, 2, 3, 5, 7, 10, 15, 20, 25, 30]


def test_recovers_planted_parameters_from_exact_data():
    # Data generated by the model itself must fit almost perfectly
    # (the 2-D lambda grid granularity is the only residual).
    planted = Svensson.Fit(0.045, -0.02, 0.03, -0.04, 1.5, 7.0, 0)
    rates = [planted.zero_rate(t) for t in TENORS]
    fit = Svensson.fit(TENORS, rates)
    assert fit.rmse < 5e-5
    assert fit.b0 == pytest.approx(0.045, abs=5e-3)
    assert fit.short_rate() == pytest.approx(0.025, abs=5e-3)   # b0 + b1
    assert fit.long_rate() == pytest.approx(0.045, abs=5e-3)
    assert fit.lambda2 > fit.lambda1, "hump ordering enforced"
    for t, r in zip(TENORS, rates):
        assert fit.zero_rate(t) == pytest.approx(r, abs=2e-4)


def test_nests_nelson_siegel_on_single_hump_data():
    # Data from a pure NS curve (b3 = 0): Svensson contains NS, so the
    # fit must reproduce it essentially exactly — the extra hump earns
    # nothing but cannot hurt in-sample.
    ns = NelsonSiegel.Fit(0.05, -0.02, 0.01, 2.0, 0)
    rates = [ns.zero_rate(t) for t in TENORS]
    sv = Svensson.fit(TENORS, rates)
    assert sv.rmse < 2e-4
    for t, r in zip(TENORS, rates):
        assert sv.zero_rate(t) == pytest.approx(r, abs=5e-4)
    assert sv.long_rate() == pytest.approx(0.05, abs=5e-3)
    assert sv.short_rate() == pytest.approx(0.03, abs=5e-3)


def test_double_hump_beats_plain_nelson_siegel():
    # A short-end bump plus a long-end dip: one hump must split the
    # difference, two humps nail it — the whole point of the model.
    planted = Svensson.Fit(0.04, -0.015, 0.05, -0.06, 0.8, 8.0, 0)
    rates = [planted.zero_rate(t) for t in TENORS]
    sv = Svensson.fit(TENORS, rates)
    ns = NelsonSiegel.fit(TENORS, rates)
    assert sv.rmse < 1e-4
    assert ns.rmse > 5 * sv.rmse, \
        f"NS rmse {ns.rmse} should be far above Svensson {sv.rmse}"


def test_gates_refuse_degenerate_input():
    ok_t = [0.5, 1, 2, 3, 5, 10]
    ok_r = [0.02, 0.025, 0.03, 0.032, 0.035, 0.037]
    with pytest.raises(ValueError):     # < 6 observations
        Svensson.fit([1, 2, 3, 4, 5], [1, 2, 3, 4, 5])
    with pytest.raises(ValueError):     # misaligned
        Svensson.fit(ok_t, [0.02, 0.025, 0.03])
    with pytest.raises(ValueError):     # zero tenor
        Svensson.fit([0, 1, 2, 3, 5, 10], ok_r)
    with pytest.raises(ValueError):     # NaN rate
        Svensson.fit(ok_t, [0.02, float("nan"), 0.03, 0.032, 0.035, 0.037])
    fit = Svensson.fit(ok_t, ok_r)
    with pytest.raises(ValueError):
        fit.zero_rate(0)
    with pytest.raises(ValueError):
        fit.zero_rate(-1)
