"""Nelson-Siegel pins, ported from Java NelsonSiegelTest.

Exact recovery of planted parameters, flat-curve exactness, and the
inversion sign (b1 > 0 when short rates sit above long rates).
"""

import pytest

from quantfinlib.rates import NelsonSiegel

TENORS = [0.25, 0.5, 1, 2, 3, 5, 7, 10, 15, 20]


def test_recovers_planted_parameters_from_exact_data():
    # Data generated by the model itself must fit almost perfectly
    # (lambda grid granularity is the only residual).
    planted = NelsonSiegel.Fit(0.05, -0.02, 0.01, 2.0, 0)
    rates = [planted.zero_rate(t) for t in TENORS]
    fit = NelsonSiegel.fit(TENORS, rates)
    assert fit.rmse < 1e-4
    assert fit.b0 == pytest.approx(0.05, abs=2e-3)
    assert fit.short_rate() == pytest.approx(0.03, abs=2e-3)   # b0 + b1
    for t, r in zip(TENORS, rates):
        assert fit.zero_rate(t) == pytest.approx(r, abs=2e-4)


def test_flat_curve_fits_exactly_at_any_lambda():
    # A constant target is in the span of the constant regressor: OLS
    # hits it exactly, whatever lambda the grid picks.
    rates = [0.04] * len(TENORS)
    fit = NelsonSiegel.fit(TENORS, rates)
    assert fit.rmse == pytest.approx(0, abs=1e-12)
    assert fit.zero_rate(0.5) == pytest.approx(0.04, abs=1e-10)
    assert fit.zero_rate(30) == pytest.approx(0.04, abs=1e-10)


def test_inverted_curve_gets_positive_slope_parameter():
    # Short rates above long rates: z(0) > z(inf) means b1 > 0 —
    # the recession-signal sign, fitted not forced.
    rates = [0.055, 0.054, 0.052, 0.049, 0.046, 0.042, 0.040, 0.038, 0.037, 0.036]
    fit = NelsonSiegel.fit(TENORS, rates)
    assert fit.b1 > 0
    assert fit.short_rate() > fit.long_rate()


def test_gates_refuse_degenerate_input():
    ok = [0.01, 0.02, 0.03, 0.04]
    with pytest.raises(ValueError):
        NelsonSiegel.fit([1, 2, 3], [0.01, 0.02, 0.03])         # < 4 observations
    with pytest.raises(ValueError):
        NelsonSiegel.fit([0, 1, 2, 3], ok)                      # zero tenor
    with pytest.raises(ValueError):
        NelsonSiegel.fit([1, 2, 3, 4], [0.01, float("nan"), 0.03, 0.04])
    fit = NelsonSiegel.fit([1, 2, 3, 4], ok)
    with pytest.raises(ValueError):
        fit.zero_rate(0)
    with pytest.raises(ValueError):
        fit.zero_rate(-1)
